### PR TITLE
Fix timestamp incorrect unit (off by 1000)

### LINKED ISSUE #28: Problem with timestamps generated for CDC records in Scylla
Hello! I'm trying to do a Kafka to Scylladb sink by using Kafka Scylla Sink Connect but I got the following error:
`Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: cdc: attempted to get a stream from an earlier generation than the currently used one. With CDC you cannot send writes with timestamps too far into the past, because that would break consistency properties (write timestamp: 1970/01/19 16:01:29, current generation started at: 2021/01/22 16:03:45)`

I have no idea from where is getting this timestamp with the date -1970/01/19.
The ScyllaDB cluster is on VM, the Kafka Broker is running on another VM and the Kafka Connect is running in a Kubernetes container. 

What I guess is causing the issue is the server time or at least the clock that Kafka Connect's Scylla client is using so I've checked the server times on the VM and in the Container and they seem to be okay (keep in mind it was needed some time between checking the server time on the different targets):
Dev Scylla VMs server time          ->  Wed 2021-02-10 14:17:19 UTC
Dev Kafka VMs server time          ->  Wed 2021-02-10 14:26:10 UTC
Dev K8s Kafka Pods  server time  ->  Wed 2021 Feb 10 14:20:09 UTC

Is there anything that can fix this? I didn't found any solution on the internet neither any Configuration Property which to do anything with that.

### PR DESCRIPTION
**Pull request by avelanarius**
Fix timestamps set on `BoundStatement`: timestamps on bound statements expect a microsecond precision, but a Kafka timestamp with a millisecond precision was set without conversion.

Fixes #28 - when a CDC table was set as a destination, a row with invalid timestamp (in year 1970 due to invalid units) would be attempted to be inserted and it would fail, as 1970 is earlier than any CDC generation.

### CODE REVIEW

File: src/main/java/io/connect/scylladb/ScyllaDbSinkTaskHelper.java [hunk 1]
```diff
@@ -95,7 +95,9 @@ public BoundStatement getBoundStatementForRecord(SinkRecord record) {
       boundStatement.setDefaultTimestamp(topicConfigs.getTimeStamp());
```
Comment (haaawk) [inline src/main/java/io/connect/scylladb/ScyllaDbSinkTaskHelper.java:95]: Is this place ok?

**Review by haaawk — APPROVED** [review]

File: src/main/java/io/connect/scylladb/ScyllaDbSinkTaskHelper.java (hunk 1 above)
Comment (avelanarius) [reply src/main/java/io/connect/scylladb/ScyllaDbSinkTaskHelper.java:95]: This gets the timestamp from `TopicConfigs` class. In `TopicConfigs` it is set in two ways: by reading the timestamp of Kafka message (this occurrence is fixed) or by reading a user-provided field (in that case the behaviour should not be changed) - therefore no `* 1000` here (only adding it to all occurances of Kafka's `record.timestamp()`).

**Comment by Psykepro** [comment]
I've tested with this change and now works this will fix my issue :) please merge it when possible:
https://github.com/scylladb/kafka-connect-scylladb/issues/28
